name: holiday_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  go_router: ^14.6.1
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  freezed: ^2.5.7
  build_runner: ^2.4.13
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
